import React from 'react'
import Selection from './Selection'

export default function GrammarSubMenu({
  wordClass,
  gender,
  setGender,
  person,
  setPerson,
  number,
  setNumber,
}) {
  return (
    <>
      {wordClass === 'N' && (
        <>
          <Selection
            text="m"
            color="var(--masculine)"
            diameter="43px"
            activeProperty={gender}
            onClick={setGender}
          />
          <Selection
            text="f"
            color="var(--feminine)"
            diameter="43px"
            activeProperty={gender}
            onClick={setGender}
          />
          <Selection
            text="n"
            color="var(--neuter)"
            diameter="43px"
            activeProperty={gender}
            onClick={setGender}
          />
        </>
      )}
      {wordClass === 'A' && (
        <>
          <Selection
            text="Sg"
            active={false}
            color="var(--singular)"
            diameter="43px"
            activeProperty={number}
            onClick={setNumber}
          />
          <Selection
            text="Pl"
            active={false}
            color="var(--plural)"
            diameter="43px"
            activeProperty={number}
            onClick={setNumber}
          />
          <Selection
            text="m"
            active={false}
            color="var(--masculine)"
            diameter="43px"
            activeProperty={gender}
            onClick={setGender}
          />
          <Selection
            text="f"
            active={false}
            color="var(--feminine)"
            diameter="43px"
            activeProperty={gender}
            onClick={setGender}
          />
        </>
      )}
      {wordClass === 'V' && (
        <>
          <Selection
            text="Sg"
            active={false}
            color="var(--singular)"
            diameter="43px"
            activeProperty={number}
            onClick={setNumber}
          />
          <Selection
            text="Pl"
            active={false}
            color="var(--plural)"
            diameter="43px"
            activeProperty={number}
            onClick={setNumber}
          />
          <Selection
            text="1"
            active={false}
            color="var(--person)"
            diameter="43px"
            activeProperty={person}
            onClick={setPerson}
          />
          <Selection
            text="2"
            active={false}
            color="var(--person)"
            diameter="43px"
            activeProperty={person}
            onClick={setPerson}
          />
          <Selection
            text="3"
            active={false}
            color="var(--person)"
            diameter="43px"
            activeProperty={person}
            onClick={setPerson}
          />
        </>
      )}
    </>
  )
}
